name: Automated Dummy Commit

on:
  push:
    branches:
      - main

jobs:
  dummy-commit:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'Dummy')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "actions@github.com"

      - name: Create an empty commit
        run: |
          git commit --allow-empty -m "Dummy"

      - name: Push empty commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git push origin main
