name: Code Formatting

on:
  pull_request:
    branches:
      - main


jobs:
  format:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: Read Node.js version from .nvmrc
        id: node
        run: |
          node_version=$(cat .nvmrc)
          echo "NODE_VERSION=$node_version" >> $GITHUB_ENV

      - name: Install Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run Prettier
        run: npx prettier --write .

      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'Apply formatting changes'
          branch: ${{ github.head_ref }}
